name: CI

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_VERSION:  3.16.3
  DART_VERSION: 3.2.3

jobs:
  # because there is no easy way to pass env variables to jobs
  versions:
    runs-on: ubuntu-latest
    outputs:
      flutter_version: ${{ steps.flutterver.outputs.FLUTTER_VERSION }}
      dart_version: ${{ steps.dartver.outputs.DART_VERSION }}
    steps:
      - id: flutterver
        run: echo "FLUTTER_VERSION=${{ env.FLUTTER_VERSION }}" >> "$GITHUB_OUTPUT"
      - id: dartver
        run: echo "DART_VERSION=${{ env.DART_VERSION }}" >> "$GITHUB_OUTPUT"

  dart:
    permissions:
      contents: read
    uses: famedly/frontend-ci-templates/.github/workflows/dart.yml@main
    needs: [versions]
    with:
      flutter_version: ${{ needs.versions.outputs.flutter_version }}
      dart_version: ${{ needs.versions.outputs.dart_version }}
    secrets:
      ssh_key: "${{ secrets.CI_SSH_PRIVATE_KEY }}"

  general:
    permissions:
      contents: read
    uses: famedly/frontend-ci-templates/.github/workflows/general.yml@main

  app_jobs:
    secrets: inherit
    uses: ./.github/workflows/app.yml
    needs: [versions]
    with:
      flutter_version: ${{ needs.versions.outputs.flutter_version }}
      dart_version: ${{ needs.versions.outputs.dart_version }}
